### ISSUE TITLE
KMZ Export For OSMAnd And Others

### ISSUE THREAD

**Issue by thegranddesign** [frillweeman/deflock#1]
I'd love to have an easy way to take this offline by importing it into a mapping application. I believe a [KMZ file](https://en.wikipedia.org/wiki/Keyhole_Markup_Language) would be the best way to approach this. The additional information about the point could be added to the description of the KML point.

Any thoughts on making this possible?

**Comment by frillweeman** [comment]
That's definitely possible, but I don't think enough people would use it to warrant adding it straight to the site, especially as cities are actively rolling out new ALPRs on a daily basis.

You can download a KML file directly form Overpass Turbo, where our data is sourced. Use the query:
```
[out:json][bbox:{{bbox}}];
node["man_made"="surveillance"]["surveillance:type"="ALPR"];
out body;
>;
out skel qt;
```
to find all ALPRs and tags in your current viewport. Remove the `[bbox:{{bbox}}]` to get all nodes worldwide.

If you want just for the US, you can use this query:
```
[out:json];
area["ISO3166-1"="US"]->.searchArea;
node["man_made"="surveillance"]["surveillance:type"="ALPR"](area.searchArea);
out body;
>;
out skel qt;
```

After running the query, the results can be exported in several formats, including KML.

**Comment by thegranddesign** [comment]
That's perfect thank you :)
